name: Build

# Put your personal access token in a repository secret named PAT for cross-repository access

on: 
  workflow_dispatch:
  push:
    branches:
    - main

env:
  PLUGIN_NAME: AutoHook
  PERSONAL_PLUGIN_REPO: InitialDet/MyDalamudPlugins

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Download Dalamud
      run: |
        # Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"   
    - name: Build
      run: |
        dotnet restore -r win ${{ env.PLUGIN_NAME }}.sln
        dotnet build --configuration Release
      env: 
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    - uses: actions/upload-artifact@v2
      with:
        name: PluginRepoZip
        path: ${{env.PLUGIN_NAME}}/bin/Release/${{env.PLUGIN_NAME}}
        if-no-files-found: error

  deploy:
    needs: build
    if: "contains(toJSON(github.event.commits.*.message), '[PUSH]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ env.PERSONAL_PLUGIN_REPO }}
        token: ${{ secrets.PAT }}
    - uses: actions/download-artifact@v2
      with:
        name: PluginRepoZip
        path: plugins/${{ env.PLUGIN_NAME }}
    - uses: EndBug/add-and-commit@v7
      with:
        add: --all
        author_name: GitHub Action
        author_email: github-actions[bot]@users.noreply.github.com
        message: Update ${{ env.PLUGIN_NAME }}
